[2024-02-21 17:39:42] INFO Watching for file changes with StatReloader
[2024-02-21 17:41:59] INFO Watching for file changes with StatReloader
[2024-02-21 17:42:14] INFO "GET / HTTP/1.1" 200 16143
[2024-02-21 17:42:18] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-21 17:42:18] INFO "GET /blog/1 HTTP/1.1" 200 17787
[2024-02-21 17:42:21] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 2
[2024-02-21 17:42:21] INFO "GET /blog/2 HTTP/1.1" 200 17894
[2024-02-21 17:43:12] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-21 17:43:12] INFO "GET /blog/1 HTTP/1.1" 200 17786
[2024-02-21 17:43:14] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 2
[2024-02-21 17:43:14] INFO "GET /blog/2 HTTP/1.1" 200 17894
[2024-02-21 17:43:16] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 3
[2024-02-21 17:43:17] INFO "GET /blog/3 HTTP/1.1" 200 17679
[2024-02-21 17:43:18] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 2
[2024-02-21 17:43:18] INFO "GET /blog/2 HTTP/1.1" 200 17893
[2024-02-21 17:43:26] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 3
[2024-02-21 17:43:27] INFO "GET /blog/3 HTTP/1.1" 200 17678
[2024-02-21 17:43:37] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 2
[2024-02-21 17:43:38] INFO "GET /blog/2 HTTP/1.1" 200 17894
[2024-02-21 17:43:45] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 3
[2024-02-21 17:43:45] INFO "GET /blog/3 HTTP/1.1" 200 17677
[2024-02-21 17:43:47] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 2
[2024-02-21 17:43:47] INFO "GET /blog/2 HTTP/1.1" 200 17894
[2024-02-21 17:43:48] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-21 17:43:48] INFO "GET /blog/1 HTTP/1.1" 200 17785
[2024-02-22 15:38:12] INFO Watching for file changes with StatReloader
[2024-02-22 15:38:17] INFO "GET / HTTP/1.1" 200 16204
[2024-02-22 15:38:17] INFO "GET /static/css/styles.css HTTP/1.1" 200 250226
[2024-02-22 15:38:18] INFO "GET /static/favicon.ico HTTP/1.1" 200 270398
[2024-02-22 16:53:32] INFO Watching for file changes with StatReloader
[2024-02-22 16:53:36] INFO "GET / HTTP/1.1" 200 16204
[2024-02-22 16:53:38] INFO "GET /admin/ HTTP/1.1" 200 17459
[2024-02-22 16:53:38] INFO "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
[2024-02-22 16:53:38] INFO "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
[2024-02-22 16:53:38] INFO "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
[2024-02-22 16:53:38] WARNING Not Found: /favicon.ico
[2024-02-22 16:53:38] WARNING "GET /favicon.ico HTTP/1.1" 404 12425
[2024-02-22 16:53:45] INFO "GET /admin/coding/pycoding/ HTTP/1.1" 200 16181
[2024-02-22 16:53:45] INFO "GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 232381
[2024-02-22 16:53:45] INFO "GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 288580
[2024-02-22 16:53:45] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 16:53:47] INFO "GET /admin/coding/pycoding/add/ HTTP/1.1" 200 20599
[2024-02-22 16:53:47] INFO "GET /static/markdownx/admin/css/markdownx.css HTTP/1.1" 200 4059
[2024-02-22 16:53:47] INFO "GET /static/admin/js/calendar.js HTTP/1.1" 200 8466
[2024-02-22 16:53:47] INFO "GET /static/markdownx/js/markdownx.js HTTP/1.1" 200 33556
[2024-02-22 16:53:47] INFO "GET /static/admin/js/admin/DateTimeShortcuts.js HTTP/1.1" 200 19379
[2024-02-22 16:53:47] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 16:53:47] INFO "GET /static/admin/img/icon-clock.svg HTTP/1.1" 200 677
[2024-02-22 16:53:47] INFO "GET /static/admin/img/icon-calendar.svg HTTP/1.1" 200 1086
[2024-02-22 16:53:48] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 0
[2024-02-22 16:54:12] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 0
[2024-02-22 16:54:12] INFO "GET /__debug__/history_sidebar/?store_id=9afee230eb584bb99a3194bc5c5d49af HTTP/1.1" 200 9519
[2024-02-22 16:54:12] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 19
[2024-02-22 16:54:12] INFO "GET /__debug__/history_sidebar/?store_id=5e9bce3aaa244d3180328dabfb185620 HTTP/1.1" 200 9519
[2024-02-22 16:54:36] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 19
[2024-02-22 16:54:36] INFO "GET /__debug__/history_sidebar/?store_id=5cfd5e3ec481459e946b8ecd8b21b7ef HTTP/1.1" 200 9519
[2024-02-22 16:54:50] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 19
[2024-02-22 16:54:50] INFO "GET /__debug__/history_sidebar/?store_id=f682248a0be14cbd915f1ea952f05b0e HTTP/1.1" 200 9519
[2024-02-22 16:55:07] INFO "POST /admin/coding/pycoding/add/ HTTP/1.1" 200 20909
[2024-02-22 16:55:07] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 16:55:07] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 19
[2024-02-22 16:55:21] INFO "POST /admin/coding/pycoding/add/ HTTP/1.1" 302 0
[2024-02-22 16:55:21] INFO "GET /admin/coding/pycoding/ HTTP/1.1" 200 17632
[2024-02-22 16:55:22] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 16:55:24] INFO "GET /admin/coding/pycoding/1/change/ HTTP/1.1" 200 21041
[2024-02-22 16:55:24] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 16:55:24] INFO "GET /static/admin/img/tooltag-arrowright.svg HTTP/1.1" 200 280
[2024-02-22 16:55:24] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 19
[2024-02-22 16:55:25] INFO "GET /admin/coding/pycoding/ HTTP/1.1" 200 17412
[2024-02-22 16:55:40] WARNING Not Found: /coding/1/
[2024-02-22 16:55:40] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 16:55:46] WARNING Not Found: /coding/0/
[2024-02-22 16:55:46] WARNING "GET /coding/0/ HTTP/1.1" 404 12417
[2024-02-22 16:57:06] INFO /Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/myapp/coding/models.py changed, reloading.
[2024-02-22 16:57:06] INFO Watching for file changes with StatReloader
[2024-02-22 16:57:12] WARNING Not Found: /coding/1/
[2024-02-22 16:57:12] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 16:57:19] INFO /Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/myapp/coding/models.py changed, reloading.
[2024-02-22 16:57:19] INFO Watching for file changes with StatReloader
[2024-02-22 16:58:06] WARNING Not Found: /coding/1/
[2024-02-22 16:58:06] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 16:58:45] INFO /Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/myapp/coding/models.py changed, reloading.
[2024-02-22 16:58:46] INFO Watching for file changes with StatReloader
[2024-02-22 16:58:49] WARNING Not Found: /coding/1/
[2024-02-22 16:58:49] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 16:58:53] WARNING Not Found: /coding/0/
[2024-02-22 16:58:53] WARNING "GET /coding/0/ HTTP/1.1" 404 12417
[2024-02-22 16:58:59] WARNING Not Found: /coding/1/
[2024-02-22 16:58:59] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:02:03] INFO Watching for file changes with StatReloader
[2024-02-22 17:02:06] WARNING Not Found: /coding/1/
[2024-02-22 17:02:06] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:02:10] WARNING Not Found: /coding/
[2024-02-22 17:02:10] WARNING "GET /coding/ HTTP/1.1" 404 12409
[2024-02-22 17:02:13] INFO "GET /admin/ HTTP/1.1" 200 17755
[2024-02-22 17:02:16] INFO "GET /admin/coding/pycoding/ HTTP/1.1" 200 17412
[2024-02-22 17:02:16] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:02:18] INFO "GET /admin/coding/pycoding/1/change/ HTTP/1.1" 200 21041
[2024-02-22 17:02:18] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:02:19] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 19
[2024-02-22 17:02:28] ERROR Internal Server Error: /admin/r/10/1/
Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/contenttypes/views.py", line 35, in shortcut
    absurl = get_absolute_url()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/myapp/coding/models.py", line 23, in get_absolute_url
    if not self.is_root():
           ^^^^^^^^^^^^
AttributeError: 'PyCoding' object has no attribute 'is_root'
[2024-02-22 17:02:28] ERROR "GET /admin/r/10/1/ HTTP/1.1" 500 97728
[2024-02-22 17:04:26] WARNING Not Found: /coding/1/
[2024-02-22 17:04:26] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:04:27] WARNING Not Found: /coding/1/
[2024-02-22 17:04:27] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:13:00] WARNING Not Found: /coding/1/
[2024-02-22 17:13:00] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:13:04] WARNING Not Found: /coding/1/
[2024-02-22 17:13:04] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:18:14] WARNING Not Found: /coding/1/
[2024-02-22 17:18:14] WARNING "GET /coding/1/ HTTP/1.1" 404 12417
[2024-02-22 17:19:44] INFO /Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/config/urls.py changed, reloading.
[2024-02-22 17:19:44] INFO Watching for file changes with StatReloader
[2024-02-22 17:19:48] INFO "GET /coding/1/ HTTP/1.1" 200 15238
[2024-02-22 17:45:03] INFO Watching for file changes with StatReloader
[2024-02-22 17:45:09] INFO "GET /admin/ HTTP/1.1" 200 17755
[2024-02-22 17:45:11] INFO "GET /admin/blog/pyblog/ HTTP/1.1" 200 18777
[2024-02-22 17:45:11] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:13] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 17917
[2024-02-22 17:45:13] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:14] INFO "GET /admin/blog/pyblogdetail/1/change/ HTTP/1.1" 200 20464
[2024-02-22 17:45:15] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:21] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 17918
[2024-02-22 17:45:21] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:22] INFO "GET /admin/blog/pyblogdetail/2/change/ HTTP/1.1" 200 20504
[2024-02-22 17:45:23] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:26] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 17917
[2024-02-22 17:45:28] INFO "GET /admin/blog/pyblogdetail/3/change/ HTTP/1.1" 200 20561
[2024-02-22 17:45:28] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:39] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 17917
[2024-02-22 17:45:40] INFO "GET /admin/blog/pyblogdetail/3/change/ HTTP/1.1" 200 20561
[2024-02-22 17:45:41] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:45:44] INFO "POST /admin/blog/pyblogdetail/3/change/ HTTP/1.1" 302 0
[2024-02-22 17:45:44] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 18154
[2024-02-22 17:45:44] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:46:01] INFO "GET /blogs/ HTTP/1.1" 200 15197
[2024-02-22 17:46:04] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-22 17:46:04] INFO "GET /blog/1 HTTP/1.1" 200 18429
[2024-02-22 17:46:04] WARNING Not Found: /Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/myapp/media/mad_pumpkin_icon.jpeg
[2024-02-22 17:46:04] WARNING "GET /Users/beomtaehyeon/Documents/GitHub_Clon/pyblog_ubuntu/myapp/media/mad_pumpkin_icon.jpeg HTTP/1.1" 404 12923
[2024-02-22 17:47:53] INFO "GET /admin/ HTTP/1.1" 200 18071
[2024-02-22 17:47:55] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 17917
[2024-02-22 17:47:55] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:48:45] INFO "GET /admin/blog/pyblogdetail/3/change/ HTTP/1.1" 200 20659
[2024-02-22 17:48:45] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:48:50] INFO "POST /admin/blog/pyblogdetail/3/change/ HTTP/1.1" 302 0
[2024-02-22 17:48:50] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 18154
[2024-02-22 17:48:50] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-22 17:48:57] INFO "GET /blogs/ HTTP/1.1" 200 15196
[2024-02-22 17:49:02] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-22 17:49:02] INFO "GET /blog/1 HTTP/1.1" 200 18348
[2024-02-22 17:49:02] WARNING Not Found: /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg
[2024-02-22 17:49:02] WARNING "GET /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg HTTP/1.1" 404 12764
[2024-02-23 15:45:52] INFO Watching for file changes with StatReloader
[2024-02-23 15:45:57] INFO "GET / HTTP/1.1" 200 16025
[2024-02-23 15:46:03] INFO "GET /blogs/ HTTP/1.1" 200 15883
[2024-02-23 15:46:05] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-23 15:46:05] INFO "GET /blog/1 HTTP/1.1" 200 18170
[2024-02-23 15:46:06] WARNING Not Found: /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg
[2024-02-23 15:46:06] WARNING "GET /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg HTTP/1.1" 404 12763
[2024-02-23 15:48:13] INFO "GET /admin/ HTTP/1.1" 200 18386
[2024-02-23 15:48:13] WARNING Not Found: /favicon.ico
[2024-02-23 15:48:13] WARNING "GET /favicon.ico HTTP/1.1" 404 12616
[2024-02-23 15:48:29] ERROR Internal Server Error: /admin/coding/pycoding/
Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/treebeard/admin.py", line 49, in changelist_view
    return super().changelist_view(request, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")
[2024-02-23 15:48:29] ERROR "GET /admin/coding/pycoding/ HTTP/1.1" 500 209161
[2024-02-23 15:48:33] INFO "GET /admin/ HTTP/1.1" 200 18386
[2024-02-23 15:48:34] INFO "GET /admin/blog/pyblog/ HTTP/1.1" 200 18777
[2024-02-23 15:48:34] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-23 15:48:35] INFO "GET /admin/ HTTP/1.1" 200 18386
[2024-02-23 15:48:36] INFO "GET /admin/blog/pyblogdetail/ HTTP/1.1" 200 17917
[2024-02-23 15:48:36] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-23 15:48:37] INFO "GET /admin/ HTTP/1.1" 200 18386
[2024-02-23 15:48:37] ERROR Internal Server Error: /admin/coding/pycoding/
Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/treebeard/admin.py", line 49, in changelist_view
    return super().changelist_view(request, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")
[2024-02-23 15:48:37] ERROR "GET /admin/coding/pycoding/ HTTP/1.1" 500 209160
[2024-02-23 15:53:40] INFO "GET /blogs/ HTTP/1.1" 200 15859
[2024-02-23 15:56:32] INFO "GET /blogs/ HTTP/1.1" 200 16117
[2024-02-23 15:56:32] INFO "GET /static/favicon.ico HTTP/1.1" 304 0
[2024-02-23 15:58:26] INFO "GET /blogs/ HTTP/1.1" 200 16117
[2024-02-23 15:58:29] INFO "GET / HTTP/1.1" 200 16258
[2024-02-23 15:58:31] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-23 15:58:31] INFO "GET /blog/1 HTTP/1.1" 200 18403
[2024-02-23 15:58:31] WARNING Not Found: /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg
[2024-02-23 15:58:31] WARNING "GET /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg HTTP/1.1" 404 12764
[2024-02-23 16:00:27] INFO "GET /blogs/ HTTP/1.1" 200 15883
[2024-02-23 16:44:36] INFO Watching for file changes with StatReloader
[2024-02-23 16:44:41] INFO "GET /admin/ HTTP/1.1" 200 18387
[2024-02-23 16:44:43] INFO "GET /admin/blog/pyblog/ HTTP/1.1" 200 18777
[2024-02-23 16:44:43] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-23 16:44:45] ERROR Internal Server Error: /admin/coding/pycoding/
Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/treebeard/admin.py", line 49, in changelist_view
    return super().changelist_view(request, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")
[2024-02-23 16:44:45] ERROR "GET /admin/coding/pycoding/ HTTP/1.1" 500 209172
[2024-02-23 17:02:23] INFO Watching for file changes with StatReloader
[2024-02-23 17:02:28] INFO "GET /admin/ HTTP/1.1" 200 18387
[2024-02-23 17:02:30] INFO "GET /admin/blog/pyblog/ HTTP/1.1" 200 18777
[2024-02-23 17:02:30] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-23 17:02:34] INFO "GET /admin/blog/pyblog/1/change/ HTTP/1.1" 200 32289
[2024-02-23 17:02:35] INFO "GET /static/markdownx/admin/css/markdownx.css HTTP/1.1" 304 0
[2024-02-23 17:02:35] INFO "GET /static/markdownx/js/markdownx.js HTTP/1.1" 304 0
[2024-02-23 17:02:35] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-23 17:02:35] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 115
[2024-02-23 17:02:35] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 0
[2024-02-23 17:02:35] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 0
[2024-02-23 17:02:35] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 0
[2024-02-23 17:02:35] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 0
[2024-02-23 17:02:42] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 115
[2024-02-23 17:02:42] INFO "GET /__debug__/history_sidebar/?store_id=d246bf789eca416d9f4649c44bc1b6ca HTTP/1.1" 200 9519
[2024-02-23 17:02:46] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 114
[2024-02-23 17:02:46] INFO "GET /__debug__/history_sidebar/?store_id=8a44afed88f14d86ade3b7c3888daa2f HTTP/1.1" 200 9519
[2024-02-23 17:02:48] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 114
[2024-02-23 17:02:48] INFO "GET /__debug__/history_sidebar/?store_id=b53f67cf807f45888138e151f01e904b HTTP/1.1" 200 9519
[2024-02-23 17:02:54] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 142
[2024-02-23 17:02:54] INFO "GET /__debug__/history_sidebar/?store_id=e37c95ef87074f9293235b4dbb3d5dae HTTP/1.1" 200 9519
[2024-02-23 17:02:56] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 148
[2024-02-23 17:02:56] INFO "GET /__debug__/history_sidebar/?store_id=8c4f128495874c2cb1d1f7abf1f25dad HTTP/1.1" 200 9519
[2024-02-23 17:03:01] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 168
[2024-02-23 17:03:01] INFO "GET /__debug__/history_sidebar/?store_id=c56d8cfc06124a4fb1557ef0b99828cd HTTP/1.1" 200 9519
[2024-02-23 17:03:09] INFO "POST /markdownx/markdownify/ HTTP/1.1" 200 168
[2024-02-23 17:03:09] INFO "GET /__debug__/history_sidebar/?store_id=c726ecbaadc048858a7e5fdc70068bed HTTP/1.1" 200 9519
[2024-02-23 17:03:12] INFO "POST /admin/blog/pyblog/1/change/ HTTP/1.1" 302 0
[2024-02-23 17:03:12] INFO "GET /admin/blog/pyblog/ HTTP/1.1" 200 18995
[2024-02-23 17:03:12] INFO "GET /admin/jsi18n/ HTTP/1.1" 200 8911
[2024-02-23 17:03:14] ERROR Internal Server Error: /admin/coding/pycoding/
Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 686, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/treebeard/admin.py", line 49, in changelist_view
    return super().changelist_view(request, extra_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/utils/decorators.py", line 133, in _wrapped_view
    response = view_func(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/contrib/admin/options.py", line 2068, in changelist_view
    "selection_note": _("0 of %(cnt)s selected") % {"cnt": len(cl.result_list)},
                                                           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")
[2024-02-23 17:03:14] ERROR "GET /admin/coding/pycoding/ HTTP/1.1" 500 209173
[2024-02-23 17:05:13] INFO "GET /__debug__/render_panel/?store_id=41df5c099e0a4ba191248d5893baae59&panel_id=RequestPanel HTTP/1.1" 200 2280
[2024-02-23 17:06:12] INFO "GET /__debug__/render_panel/?store_id=41df5c099e0a4ba191248d5893baae59&panel_id=SQLPanel HTTP/1.1" 200 77643
[2024-02-23 17:06:48] INFO "GET /blogs/ HTTP/1.1" 200 15883
[2024-02-23 17:06:50] INFO SELECT `py_blog`.`id`, `py_blog`.`title`, `py_blog`.`update_dt`, `py_blog`.`regist_dt` FROM `py_blog` WHERE `py_blog`.`id` = 1
[2024-02-23 17:06:50] INFO "GET /blog/1 HTTP/1.1" 200 18223
[2024-02-23 17:06:51] WARNING Not Found: /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg
[2024-02-23 17:06:51] WARNING "GET /Users/beomtaehyeon/Desktop/mad_pumpkin_icon.jpeg HTTP/1.1" 404 12763
[2024-02-24 15:10:56] INFO Watching for file changes with StatReloader
[2024-02-24 15:11:02] INFO "GET / HTTP/1.1" 200 16025
[2024-02-24 15:11:02] INFO "GET /static/debug_toolbar/css/toolbar.css HTTP/1.1" 304 0
[2024-02-24 15:11:02] INFO "GET /static/debug_toolbar/js/toolbar.js HTTP/1.1" 304 0
[2024-02-24 15:11:02] INFO "GET /static/debug_toolbar/css/print.css HTTP/1.1" 304 0
[2024-02-24 15:11:02] INFO "GET /static/debug_toolbar/js/utils.js HTTP/1.1" 304 0
[2024-02-24 15:11:12] INFO "GET /blogs/ HTTP/1.1" 200 15883
[2024-02-24 15:12:42] ERROR Internal Server Error: /coding/1/
Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/generic/base.py", line 142, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/generic/detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/views/generic/detail.py", line 53, in get_object
    obj = queryset.get()
          ^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 646, in get
    num = len(clone)
          ^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 376, in __len__
    self._fetch_all()
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 1866, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/query.py", line 87, in __iter__
    results = compiler.execute_sql(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/models/sql/compiler.py", line 1395, in execute_sql
    cursor.execute(sql, params)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 252, in execute
    return self._record(super().execute, sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/debug_toolbar/panels/sql/tracking.py", line 177, in _record
    return method(sql, params)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 84, in _execute
    with self.db.wrap_database_errors:
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/django/db/backends/mysql/base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 179, in execute
    res = self._query(mogrified_query)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/cursors.py", line 330, in _query
    db.query(q)
  File "/Users/beomtaehyeon/miniforge3/envs/pyblog/lib/python3.12/site-packages/MySQLdb/connections.py", line 257, in query
    _mysql.connection.query(self, query)
django.db.utils.OperationalError: (1054, "Unknown column 'py_coding.path' in 'field list'")
[2024-02-24 15:12:42] ERROR "GET /coding/1/ HTTP/1.1" 500 191521
[2024-02-24 15:12:43] WARNING Not Found: /favicon.ico
[2024-02-24 15:12:43] WARNING "GET /favicon.ico HTTP/1.1" 404 12615
